### ISSUE TITLE
`helm-dash-docset-installed-p` sometimes confuses underscores and version numbers.

### ISSUE THREAD

**Issue by ebobby** [dash-docs-el/helm-dash#168]
Maybe it is me trying to be clever but if I want to install `"Ruby_on_Rails_5"` but not re install it I have to call `helm-dash-docset-installed-p` with `Ruby on Rails`.

Would it be worth while to make it so `helm-dash-docset-installed-p` works when you pass it the same value that to pass to `helm-dash-install-docset` ?

For example, I had to get a bit crafty on my own config to avoid downloading the same docset all the time:

https://github.com/ebobby/emacs.d/commit/9120c83ffce46a51e1f103149894fc72aa562088

I am happy to provide a PR unless the way it works is the correct way for reasons that I may not understand.

**Comment by kidd** [comment]
Hola!

AFAIR the docset tgz names do not have any correspondence with the directory the unzip to. For example, All Lua docsets, which have different urls (obviously), so different tgz filenames, unzip to "Lua" directory.  

It's quite a big mess, but if you find a way to cover most of the cases, and doesn't imply any regression, I'd be happy to merge it.  
Try with Lua, RoR and Common Lisp (space vs underscore). 

Thanks for the interest, and yeah, definitely it would be nice if we could find a way to fix it. I'm just not sure it's possible.
Good luck!
